dist: trusty
env:
  matrix:
  - MOZ_HEADLESS=1
  global:
  - secure: RqXWwmxQiMubiNelSfPHaUmJyvP5aN8GAta/FC7wSS7dVR37EWdPUIeQjkQh68gjqjWORdVlmH3Nx+CgDDf7VwLG+hjYTk0uz6Oe4eWq+6IiZzlQA2H8VKKMYG/AvTPaJgCn8NDOmkWaqfPnj9MUJ1iVLqrekn5tWQs4V1naUIaHVSa+KqcDYB4RDDY6xruWENU7yFKF5EbgfTzSVTosJYdsenki88uuHkynXYk/tD6L9x5bxlSWmNsA5mOJjLZsqQ5ksg/UWWYLujWQwZ6Mll1R6sMgyjAlQJAmhsqZ/IV+s/8s/tWCjaMIuLi9f6jRVUyW73G0EEUxoFT0btXYlSCTekMcj1MQtKlU01YrR/WoMpiAie/ces3TtUKG/w0vLQu1EZNEEXX3BPXJ/04I/QLcSOVlwHEsOCF0YbcUgQQNM9JTD0tDrzvcaEdzcVbUo1VKvLvWsDsVbOSJf+Mt54X8GEl3oI7lBtvS+TQWINkk+fk7wSTSblYw9Gum6cv7wzzlLz2gk3YtyrmGv6hApwefZPGufpVrI5YaisLSag5WXdcDJSY4kGRkejPsJyReofaHdm/29phAe8UQrUviziaG78DhtPISki/CYJVjOU2h8ioxaTT+ce+IooNJBH1fggfafus+YwDV27d8K61tw0xzxso3GR04Fd9MPgHyZ24=
  - secure: fgS23xy/cmxPnYhpbesxZePRR22XfEIAUHXSgctXUeoMvZ87ijnRvZYjPZDbCaz37Lk0CrQup4/f64evxSDXzXvXUSjwBN4/A4ibOK/tIQmZhizKSAtm9qYzv5jsGqjbbQgJPeK64dlQEqzpfV3kZJ8zC3+fJ7puNpUfr7ZMBpu65xCJFtYNJ84K9puV0PEoVePsGVwLa03p3eX+WA1mLucHZR2YAd59FdalkMGWPXyutnOeUBifhKpyG1jSOGNuyixCps3u9MxFPrE1cQL3njbv/hCiPiKYHw/gvyA34HEO1vkxwBtxncCmlzU2gPd1PIQDRXBGf8hR0xApbvYwxmZIA4J0nvvdBYMrQEJaV5DbsaD+PFxDGQS6gFIiTtlfjD+IFA7yeE1J8J9SB6b8xqbHnNvAea1j5sN6AeSuetmCWS3r/IPAnhhcplMqjtouX9A7DjuKBwIitW1HsfP1b9XSDFY5xFNTy1RD3LhfNJWwmMSvHPreSFCXQQjnxknN8FxHMMWj6qzt9FTRnH4R7AxIgyCqzCMS0HqbGkzUNHuduC61rHNf4ePNEG+XWV0qQfZ2m+OJ+xgh/93XjNfrvBsq/dzmRdth2qTozOwCBLh+SS/Yq4z0nmiXt9HqBm9+IoA1nFT6rLkHKeN42RQrkyHXWYi6h3zrmUYNnz9/B5Y=
  - secure: OTz0NtCNnL5Mx99rhmC0B4E/WAEay+00wtiviu+GmBkxvB1nCfiokvaXI7CR+ltNWHgzBAcfempxK5QhRxX2THnO6TqQ0FZJv1XknddRNQldr0etwMfYKFnlwBbxM3vntarECjUrPOU44clxm7+oja76e0TAc5PXwfEPD6ImcSUtlwzeLE1aAZ83N4Alm40wZjddNAK+T87hZlbYA8Du7q1JfK11PHK1bFwd4oDS/hqSw51ROrtiSMW5lg3KZ401i5v0qA11pzx6NRbtCTpn/ZejJwU3bduI7bu2ivwbypXC2MFT50VUgSCiOUhY86uTJqr/L3URv7YTIuZJMRpgP9TBjuzJt7gHTzroqbk6ExML2reiSgH+Z1aJC4tyxhZi+cZgpmrSH628AP2Jr3vhT4RRJvsy1OlHDgcRRWWY2XgnDnKEmqH275E4wYeJEpGOc5gHuPPT2kZ6lpWOJJc6S2qcLaNawGg0GCed6yy7bkrRYOcJCYq8tHDG6pGkQ1/h9G5UpSmlU+EY6dqWO+oPlgpMINMYJoc9W2mKIz1twzxI3mRe2PkPuyvs9m+1vPffEmUuSekWgi4/z9fFLEOY11LhbxUg5JfRb9h9jj18PpP8BogeqpGFtE005fv3cBX7F9aKB++RHDyvxZnroTQcnMoG0WL/awFwEjJvNap4sSc=
addons:
  firefox: latest
  chrome: stable
sudo: required
language: java
cache:
  directories:
  - "$HOME/.gradle"
jdk:
- oraclejdk8
before_script:
- rm -rf target
script:
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis-build-pr.sh; fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis-build.sh; fi
